### ISSUE TITLE
Select button not working anymore

### ISSUE THREAD

**Issue by karlvr** [petrockblog/Xarcade2Jstick#11]
There's something about sending two keys to `uinput_kbd_write` in a row that isn't working for me under RetroPie 3.3.1 or 3.4. This manifests as my select button not working in advmame. I can't set that key to be anything. The key works in Emulation Station, so I guess it's an issue with advmame?

I notice that earlier versions of xarcade2jstick made sure they didn't send two `uinput_kbd_write` calls in one turn around that read loop. Maybe there was some significance there that we've lost in @aristeu's recent commits?

I have corrected this problem for myself with some slightly hacky code that undoes some of the good changes that @aristeu made... I'm going to improve that, but want to check whether anyone else is experiencing this same problem?

**Comment by aristeu** [comment]
Keyboard events shouldn't be a problem to send multiple but since it's BTN_SELECT and it's a gamepad, it might require a SYNC

**Comment by aristeu** [comment]
uinput_gpad_write() already sends a sync every button pressed. Other than the fact BTN_SELECT only goes out when the key is released, I'd guess advmame is expecting value 2 (repeat) from the event instead of 1? Karl, can you please replace the value to "2" instead of one and see if it fixes it? I don't have advmame here.

**Comment by karlvr** [comment]
@aristeu I'll check now; just gotta kick some kids off Minecraft videos :-) I don't _think_ it's looking for a 2; I'm not sending a 2 ever as the logic is always `xarcdev.ev[ctr].value > 0` which converts everything to 0s and 1s. Maybe it wants more than one 1? I'll test a few things.

Here's roughly what I did to solve it:

```c
	while (1) {
		if (fakeKeycode != 0) {
			/* send the keydown event for the fakeKeycode */
			uinput_kbd_write(&uinp_kbd, fakeKeycode, 1, EV_KEY);
		}

		rd = input_xarcade_read(&xarcdev);
		if (rd < 0) {
			break;
		}

		if (fakeKeycode != 0) {
			/* send the keyup event for the fakeKeycode - must happen after we read from device */
			uinput_kbd_write(&uinp_kbd, fakeKeycode, 0, EV_KEY);
			fakeKeycode = 0;
		}
```

and then a little later on:

```c
					/* combination with the other side button, quit */
					if (keyStates[KEY_3] && keyStates[KEY_4]) {
						fakeKeycode = KEY_ESC;
						// keyStates[KEY_3] = keyStates[KEY_4] = 0;
						break;
					}
```

**Comment by karlvr** [comment]
@aristeu It didn't work.

Some more investigation:

I've logged out the values of `xarcdev.ev[ctr].value` in the `KEY_3` case and I'm only receiving 1s and 0s from the Xarcade. I have to noticeably hold down the key to generate 2s. When I send these presses straight on as `BTN_SELECT` using the logic `xarcdev.ev[ctr].value > 0` for `keyvalue`, it is working fine in advmame.

**Comment by karlvr** [comment]
OK, I've figured out what advmame wants. It's a little sleep. I tried this before last night with various values, but I hadn't worked out 100% yet that advmame needs to be restarted after restarting xarcade2jstick.

So, what advmame wants is a little sleep between the down and up events. I found that `usleep(10000)` worked maybe 5% of the time, maybe less. But `usleep(100000)` works 100% of the time. So that's 1/10th of a second if I counted my zeros correctly.

**Comment by karlvr** [comment]
That PR is code that is currently working nicely for me. Both kbd and gpad events required the sleep with advmame.

**Comment by aristeu** [comment]
Great! Patch looks fine to me. The delay isn't much of a problem since isn't a button you'll be pressing a lot.

**Comment by karlvr** [comment]
Heh, quite true. Thank you.

**Comment by petrockblog** [comment]
I think we can close this issue now that the PR is merged?

**Comment by karlvr** [comment]
Absolutely. Thank YOU both. Without this I'd have a big useless hunk of plastic and wood in my lounge.
