### ISSUE TITLE
Suggestion: Don't enable the service by default

### ISSUE THREAD

**Issue by karlvr** [petrockblog/Xarcade2Jstick#16]
With the new udev support it is no longer necessary to have the xarcade2jstick start as a service. In fact, it would be possible to have xarcade2jstick installed by default in RetroPie and it would just sit there not running, waiting for a compatible device to be plugged in. And then in an uncertain future, when I install a new RetroPie image everything will just work! That's a sweet sweet future ;-)

As @aristeu said, the service may still be useful to someone, but perhaps not in the default case? As it stands; on my RetroPie udev starts xarcade2jstick before the service is started, so the service start fails and possibly causes some issues...

If I try to start the service while ES is running it actually crashes ES, something about a number of joysticks, even though xarcade2jstick actually fails to start:

```
[Xarcade2Joystick] Getting exclusive access: Found /dev/input/event0 (XGaming X-Arcade)
```

So maybe it is actually undesirable to install both ways?

**Comment by aristeu** [comment]
Problem comes from this:
        uinput_gpad_open(&uinp_gpads[0], UINPUT_GPAD_TYPE_XARCADE, 0);
        uinput_gpad_open(&uinp_gpads[1], UINPUT_GPAD_TYPE_XARCADE, 1);
        uinput_kbd_open(&uinp_kbd);
        printf("[Xarcade2Joystick] Getting exclusive access: ");
        result = input_xarcade_open(&xarcdev, INPUT_XARC_TYPE_TANKSTICK);

It first registers the two virtual gamepads and keyboard then tries to open the Xarcade event device
then fails to grab the event device (another xarcade2jstick is running) and finished taking the virtual
devices with it. I suspect ES can't handle devices disappearing that fast and crashes too.
Simply swapping should be enough.

**Comment by karlvr** [comment]
As in swapping the order in which those things happen? Open the xarcade first? That sounds like a great idea. Will you do that? I've just left the house!

**Comment by karlvr** [comment]
I'm checking this out now and will do a PR.

**Comment by karlvr** [comment]
It's harder to reproduce the issue on RetroPie 3.4, but a while loop starting xarcade2jstick successfully crashes Emulation Station after about 5 seconds. Also frustratingly on 3.4 it crashes out to a console, and my connected keyboard doesn't even work at that console. On 3.3 it just restarted ES.

After swapping those lines around it does not appear to be crashable any more. Thank you!

**Comment by karlvr** [comment]
The issue of running xarcade2jstick twice is now solved. I'd like to revisit the issue of the service. The more I think about it, the more xarcade2jstick is no longer designed to be a service, since it exits once it can no longer read from the device. It would be great to get your thoughts on that @aristeu and @petrockblog! I'll do a PR for it as well so we can see what it's like.

Using the same installservice / uninstallservice Make command to install / uninstall udev (#21) would retain compatibility with `retropie_setup.sh`. I'd need to also work out how to get udev to detect an already plugged in Xarcade; or just run xarcade2jstick from the make, much the way the current Makefile starts the service!
