### ISSUE TITLE
KEY_TAB and KEY_6 etc

### ISSUE THREAD

**Issue by karlvr** [petrockblog/Xarcade2Jstick#18]
I actually quite liked the `KEY_TAB` thing that we had before. It meant I could pretty much configure Mame without having to attach a keyboard. Not that it's a big issue, one isn't often configuring, but it was kind of nice.

Out of the box my MAME is setup so `KEY_5` is coin 1 and `KEY_6` is coin 2. So I am wondering about the use of `KEY_6` and `KEY_7` for those functions respectively from @aristeu's change. I think my mame4all is the same by default. I guess those keys are defaults in another emulator? Certainly on MAME it appears to me that they would be most useful as 5 and 6.

That being said, I change the key mappings in MAME to use the select buttons as coin buttons!

We've got more combos we could play with I think? `KEY_1` and `KEY_2` or `KEY_2` and `KEY_3` or `KEY_1` and `KEY_4`? Perhaps there's room for a tab in there?

**Comment by aristeu** [comment]
Definitely. I ended up being a bit selfish there. I thought Florian would end up just getting the first patch, not the second :^)
The logic is all there to add more combinations. We could revert the previous mapping if desirable too and add KEY_6, KEY_7 to something else.

**Comment by karlvr** [comment]
The original key combos were P1 select + start = TAB, and P2 select + start = ESC. Obviously both of these combos are more suited to something to do with each player, rather than being generic commands such as TAB and ESC. However there are probably people out there using them.

I have made a patch that puts TAB on P1 start + P2 start, keeps ESC on P1 select + P2 select and changes P1 select + start and P2 select + start to 5 and 6 respectively. I believe 5 and 6 are more standard settings for coin 1 and coin 2? Perhaps we next get to a configuration file that maps everything!

**Comment by aristeu** [comment]
Sounds good to me. I'd prefer keeping just the side button as modifier in order to not make the logic more complicated, but this works.
