### ISSUE TITLE
XBox Controller Compatability

### ISSUE THREAD

**Issue by Enverex** [petrockblog/Xarcade2Jstick#2]
Some games (Specifically through Steam) on Linux still seem to expect an XBox controller rather than a normal controller. Is it possible to edit the source of this in such a way that it would work the same way as an XBox controller on Linux?

**Comment by petrockblog** [comment]
I am sure that you can use these sources a a base for your intentions. However, this is a driver especially for the Xarcade Tankstick and not for an Xbox controller.
