### ISSUE TITLE
Start on boot failing on RetroPie 3.4

### ISSUE THREAD

**Issue by karlvr** [petrockblog/Xarcade2Jstick#20]
I am finding that xarcade2jstick fails to open the Xarcade device on boot. Either as a service or via udev. This same behaviour occurred before I switched the order of opening the devices (5f86d1049e2cbe73262423dd1fd45b6384fc971c), so I don't think it's that.

I am currently debugging this.

**Comment by karlvr** [comment]
It also appears that udev is starting xarcade2stick four times on boot. One time it is getting the device, three times it fails. But the one time that it gets the device it then goes to read from it the first time and then dies. I've tried trapping signals and I haven't found a signal that it's receiving to kill it... no more info yet.

**Comment by karlvr** [comment]
@aristeu It appears that on RetroPie 3.4 / Jessie udev kills the detached xarcade2jstick instance; it never returns from the first read it attempts.

I have switched it to a systemd unit and it now appears to work nicely. I am preparing a PR, but I am going back to test on RetroPie 3.3 / Wheezy first.

Odd that the behaviour of udev changed... I'm still not sure I understand that.

**Comment by karlvr** [comment]
More information, see the RUN section: http://www.freedesktop.org/software/systemd/man/udev.html

> Starting daemons or other long-running processes is not appropriate for udev; the forked processes, detached or not, will be unconditionally killed after the event handling has finished.

I am working on automatically choosing which approach to use.

**Comment by karlvr** [comment]
This issue will be closed by #23

**Comment by aristeu** [comment]
We *could* get the hotplug code from wdaemon[1] but I was trying to avoid it.
If udev still kills the daemon (which is weird because it was supposed to be
completely detached) or it simply isn't the right to do we can do it.

wdaemon also has support for configuration which could be reused.

[1] http://linuxwacom.sourceforge.net/wiki/index.php/Wdaemon

-- 
Aristeu

**Comment by karlvr** [comment]
Right, yes. That would be a return to a more service-based, rather than on-demand, approach. Xarcade2jstick could wait for the device to be reconnected and continue passing keys to the virtual devices. 

I think the current setup is cleaner and simpler, with a simple life cycle. Systemd is what is intended to be used to do this stuff now though, so I suggest we use it.
