### ISSUE TITLE
New keys are problematic with two players

### ISSUE THREAD

**Issue by karlvr** [petrockblog/Xarcade2Jstick#26]
Particularly ESC mapped to P1 select + P2 select. I map the select buttons to coin buttons. Both my kids like to insert coins, and they occasionally do it at the same time.

Given the two player nature of the device, I think it's safer to have our combos limited to something that a single player has to do. So I think we should revert back to the original combos of P1 select + P1 start and P2 select + P2 start :-(

/cc @aristeu

**Comment by aristeu** [comment]
In this sense P1 start + P2 start as combo is a bad idea too. need to restrict then to P1 select + something.
