### ISSUE TITLE
[suggestion] Open xarcade2jstick to other keyboard encoders

### ISSUE THREAD

**Issue by substring** [petrockblog/Xarcade2Jstick#29]
Hey
this project is great. But why restrict it to just xarcade stuff ? There are so many keyboard encoders that have almost the default MAME mapping, like the xarcade, and that could work straight away with xarcade2jstick !
I made a quick test with an IPAC2, and it was perfect !

What do you think ?

**Comment by petrockblog** [comment]
Good point! Do you have suggestions for changes?

**Comment by substring** [comment]
Yes I do !
Been thinking about this for a moment, but didn't patch it yet as my C skill are rusty ...

So :
- allow xarcade2jstick to take 1 parameter : /dev/input/eventX
- if an argument is passed, bypass the loop checking for a valid xarcade device, and just open straight away the event. Make sure it has the expected keys

If you want to take it to the next level : add configuration file support that can dynamically map the joypads (but that's much more work) and get rid of the hard coded mapping. Easy job for a C guru

Xarcade2jstick is really a great software dude, you did a great and helpful job with it :)

**Comment by substring** [comment]
looks like you're not interested
