### ISSUE TITLE
Errors installing Xarcade2Jstick

### ISSUE THREAD

**Issue by InnerMobius** [petrockblog/Xarcade2Jstick#44]
When cd'ing into /Xarcade2Jstick/ and typing "make", this is what happens:

CC input_carcade.c
In file included from input_xarcade.c:19:0:
/usr/include/glob.h:21:23: fatal error: sys/cdefs.h: No such file or directory
 #include <sys/cdefs.h>
**(filler for placement of )**^
compilation terminated.
Makefile:17: recipe for target ' ../build/input_xarcade.o' failed
make[1]" *** [../build/input_xarcade.o] Error 1
make[1] Leaving directory '/home/pi/Xarcade2Jstick/src'
Makefile:16: recipe for target 'all' failed
make: *** [all] Error 2

The trackball works great, that's not the issue. Whenever I try to remap the controls, the Tankstick is still seen as a keyboard instead of 2 gamepads. Any idea on how to fix this? I can't do any of the next steps until this is finished.

It's worth noting that I had this problem with an installation of RetroPie that I've had for a year, but only recently got a tankstick, so I did a factory reset on my installation and I'm still having this issue with Xarcade2Jstick.

**Comment by X-Arcade** [comment]
Try this: https://support.xgaming.com/support/solutions/articles/5000554993-how-to-use-x-arcade-with-raspberry-pi
