### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by poppacass78** [petrockblog/Xarcade2Jstick#47]
when typing 
git clone https://github.com/petrockblog/Xarcade2.Jstick 
as the first command on my raspberry pi 3b+ w retropie... it then asks username for https://github.com.. so i enter my usernamthen is asks for password..
but wont let me enter the pw..
eitherway its not supposed to ask fir any of that right.. im just supposed to put the first cnd line in.. then a cd cmd line then make.. but i cant get passed the first cmd without running into that login stuff.. 
i just wanna use my new controllet.. what fo i do?

**Comment by ba-seattle** [comment]
I believe the question is about being prompt for a username/pwd in github - even when entering the exact command as above users are being prompted for a un/pwd.

**Comment by petrockblog** [comment]
@Enverex is correct with the command. And it does not prompt for a username / password.
