### ISSUE TITLE
Hang for 60s x 2 on boot

### ISSUE THREAD

**Issue by karlvr** [petrockblog/Xarcade2Jstick#9]
On boot it appears that xarcade2jstick is being launched by udev, but is not exiting immediately so it hangs udev.

Referring to http://www.reactivated.net/writing_udev_rules.html#external-run it appears that `RUN` commands shouldn't take too long to run.

However xarcade2jstick doesn't exit immediately, it hangs on. We might need to implement a fork mode?

(Tested on RetroPie 3.3.1)

**Comment by karlvr** [comment]
Also I'm thinking that with the udev approach we really don't need the service anymore? So we should be getting rid of that. udev seems like the ideal way to handle it!

**Comment by aristeu** [comment]
Oops, yes, it might be needed to fork and exit. I'll take a look at it today. About the the service, it might
be useful to someone.
